### ISSUE TITLE
Break up long paragraphs

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/legalmattic#18]
Although I like the language in the terms and conditions a lot, the structure of the document itself detracts from the accessibility of the terms.

I understand that the convention is large blocks of text instead of more, smaller, and nested paragraphs. At the same time, it would really help if the larger blocks of text are broken up into smaller paragraphs of roughly two sentences each.

Visually, it makes the text look less intimidating and easier to read.

**Comment by clickysteve** [comment]
Hey, thanks for taking the time to read over the Terms and give some feedback!

There's actually two things at play here:

1. Some of the formatting of the Terms of Service from wordpress.com/tos was lost in the conversion to MarkDown for GitHub, so I have corrected this in the latest commit.
2. The 'Responsibilities of Contributors' section has a large block of text. This is actually a formatting issue rather than a preference one (I believe), as the current stylesheet on wordpress.com/tos doesn't allow for linebreaks between list items. Leave this one with me, and I'll investigate...

**Comment by pauljacobson** [comment]
No problem, let me know if you need some help with the text layout? I've been writing legal terms in Markdown for several years.

**Comment by clickysteve** [comment]
Closing out this issue as it's a legacy one, and something that's being addressed elsewhere.
